// <auto-generated />
namespace bit285_lucky_number_viewmodel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Lucky : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lucky));
        
        string IMigrationMetadata.Id
        {
            get { return "201802012330025_Lucky"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
